server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/cinevision?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:replace_this_with_a_secure_random_secret}
  expiration-ms: ${JWT_EXP_MS:3600000} # 1 hour
