server:
  port: 8081

spring:
  application:
    name: auth-service

  spring:
    datasource:
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:replace_this_with_a_secure_random_secret}
  expiration-ms: ${JWT_EXP_MS:3600000} # 1 hour
