name: Auth Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 (Spring Boot 3.x requires 17+)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build with Maven (skip tests to avoid DB issues in CI)
      - name: Build with Maven (skip tests)
        run: mvn -B -f auth-service/pom.xml clean package -DskipTests

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=naveen240720/springboot-backend
          IMAGE_TAG=auth-latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./auth-service
          docker push $IMAGE_NAME:$IMAGE_TAG
