name: Auth Service CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java (Spring Boot needs it)
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # 3. Build the project using Maven
      - name: Build with Maven
        run: mvn -B -f auth-service/pom.xml clean package

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build Docker image for auth-service
      - name: Build Docker image
        run: docker build ./auth-service -t naveen240720/springboot-backend:auth-latest

      # 6. Push image to Docker Hub
      - name: Push Docker image
        run: docker push naveen240720/springboot-backend:auth-latest
